<?php
require __DIR__.'/vendor/autoload.php';
$app = require __DIR__.'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Illuminate\Support\Facades\DB;

DB::table('service_areas')->truncate();

$now = now();
$areas = [
    ['name'=>'Jadavpur','slug'=>'jadavpur','zone'=>'South Kolkata & Jadavpur Zone','zone_slug'=>'south-kolkata-jadavpur','pin_codes'=>'["700032"]','distance_km'=>'0 to 3 km','latitude'=>22.4987,'longitude'=>88.3714,'meta_title'=>'AC Service in Jadavpur | Repair, Installation & Maintenance | Cooling Kolkata','meta_description'=>'Expert AC repair, installation & servicing in Jadavpur, Kolkata 700032. Same-day onsite visits by certified technicians. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Jadavpur, Kolkata – 700032','intro_text'=>'Cooling Kolkata provides expert onsite AC repair, installation, and maintenance in Jadavpur and surrounding areas (Chittaranjan Colony, 8B Bus Stand, Sukanta Setu). Our certified technicians offer same-day service across PIN 700032.','is_active'=>1,'sort_order'=>1,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Baghajatin & Bikramgarh','slug'=>'baghajatin-bikramgarh','zone'=>'South Kolkata & Jadavpur Zone','zone_slug'=>'south-kolkata-jadavpur','pin_codes'=>'["700086","700032"]','distance_km'=>'0 to 3 km','latitude'=>22.4850,'longitude'=>88.3780,'meta_title'=>'AC Service in Baghajatin & Bikramgarh | Repair & Installation | Cooling Kolkata','meta_description'=>'AC repair and servicing in Baghajatin & Bikramgarh, Kolkata (700086 / 700032). Fast onsite response. Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Baghajatin & Bikramgarh, Kolkata','intro_text'=>'Cooling Kolkata serves Baghajatin and Bikramgarh with professional AC repair, gas charging, and annual maintenance contracts. We cover PIN codes 700086 and 700032 with same-day technician dispatch.','is_active'=>1,'sort_order'=>2,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Garia, Patuli & Baishnabghata','slug'=>'garia-patuli-baishnabghata','zone'=>'South Kolkata & Jadavpur Zone','zone_slug'=>'south-kolkata-jadavpur','pin_codes'=>'["700094","700084"]','distance_km'=>'0 to 3 km','latitude'=>22.4635,'longitude'=>88.3879,'meta_title'=>'AC Service in Garia | Patuli & Baishnabghata AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Garia, Patuli & Baishnabghata, Kolkata (700094 / 700084). Same-day service. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Garia, Patuli & Baishnabghata – 700094 / 700084','intro_text'=>'Looking for AC repair near Garia Metro or Patuli Lake? Cooling Kolkata covers Garia, Patuli, and Baishnabghata with fast onsite AC servicing for all brands including Voltas, LG, Daikin, and Samsung.','is_active'=>1,'sort_order'=>3,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Santoshpur & Survey Park','slug'=>'santoshpur-survey-park','zone'=>'South Kolkata & Jadavpur Zone','zone_slug'=>'south-kolkata-jadavpur','pin_codes'=>'["700075"]','distance_km'=>'0 to 3 km','latitude'=>22.5020,'longitude'=>88.3950,'meta_title'=>'AC Service in Santoshpur & Survey Park | Repair & Maintenance | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Santoshpur & Survey Park, Kolkata 700075. Certified technicians, transparent pricing. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Santoshpur & Survey Park, Kolkata – 700075','intro_text'=>'Cooling Kolkata offers reliable AC repair and maintenance in Santoshpur and Survey Park (PIN 700075). Our technicians are familiar with local high-rise and residential layouts, ensuring efficient same-day onsite service.','is_active'=>1,'sort_order'=>4,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Dhakuria & Jodhpur Park','slug'=>'dhakuria-jodhpur-park','zone'=>'South Kolkata & Jadavpur Zone','zone_slug'=>'south-kolkata-jadavpur','pin_codes'=>'["700031","700068"]','distance_km'=>'0 to 3 km','latitude'=>22.5100,'longitude'=>88.3620,'meta_title'=>'AC Service in Dhakuria & Jodhpur Park | Repair & Installation | Cooling Kolkata','meta_description'=>'AC repair & servicing in Dhakuria & Jodhpur Park, Kolkata (700031 / 700068). Same-day onsite visits. Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Dhakuria & Jodhpur Park, Kolkata','intro_text'=>'Cooling Kolkata provides AC repair, installation, and AMC plans for homes and offices in Dhakuria and Jodhpur Park (PIN 700031 / 700068). Fast dispatch, genuine spare parts, and transparent pricing.','is_active'=>1,'sort_order'=>5,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Ruby, Kasba, Rajdanga & Haltu','slug'=>'ruby-kasba-rajdanga-haltu','zone'=>'South-East & EM Bypass Zone','zone_slug'=>'south-east-em-bypass','pin_codes'=>'["700107","700078"]','distance_km'=>'3 to 6 km','latitude'=>22.5180,'longitude'=>88.4010,'meta_title'=>'AC Service in Kasba & Ruby | Rajdanga & Haltu AC Repair | Cooling Kolkata','meta_description'=>'AC repair & installation in Ruby Crossing, Kasba, Rajdanga & Haltu, Kolkata (700107 / 700078). Quick onsite service. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Ruby, Kasba, Rajdanga & Haltu – 700107 / 700078','intro_text'=>'Cooling Kolkata serves the Ruby Crossing, Kasba, Rajdanga, and Haltu corridors along EM Bypass. Whether you need emergency AC repair or a new split AC installation, our team is available 6 days a week across PIN 700107 and 700078.','is_active'=>1,'sort_order'=>6,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Mukundapur, Anandapur & Nayabad','slug'=>'mukundapur-anandapur-nayabad','zone'=>'South-East & EM Bypass Zone','zone_slug'=>'south-east-em-bypass','pin_codes'=>'["700099","700150"]','distance_km'=>'3 to 6 km','latitude'=>22.4920,'longitude'=>88.4130,'meta_title'=>'AC Service in Mukundapur & Anandapur | Nayabad AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Mukundapur, Anandapur & Nayabad, Kolkata (700099 / 700150). Expert technicians. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Mukundapur, Anandapur & Nayabad, Kolkata','intro_text'=>'Residents of Mukundapur, Anandapur, and Nayabad can book Cooling Kolkata for fast AC repair and maintenance. We cover PIN codes 700099 and 700150 with same-day technician visits for all major AC brands.','is_active'=>1,'sort_order'=>7,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Kamalgazi & Narendrapur','slug'=>'kamalgazi-narendrapur','zone'=>'South-East & EM Bypass Zone','zone_slug'=>'south-east-em-bypass','pin_codes'=>'["700103"]','distance_km'=>'3 to 6 km','latitude'=>22.4460,'longitude'=>88.4050,'meta_title'=>'AC Service in Kamalgazi & Narendrapur | Repair & Maintenance | Cooling Kolkata','meta_description'=>'AC repair, installation & maintenance in Kamalgazi & Narendrapur, Kolkata 700103. Onsite same-day service. Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Kamalgazi & Narendrapur, Kolkata – 700103','intro_text'=>'Cooling Kolkata extends its AC service network to Kamalgazi and Narendrapur (PIN 700103). From routine servicing to gas top-up and PCB repairs, our team ensures your AC performs.','is_active'=>1,'sort_order'=>8,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Sonarpur','slug'=>'sonarpur','zone'=>'South-East & EM Bypass Zone','zone_slug'=>'south-east-em-bypass','pin_codes'=>'["700150"]','distance_km'=>'3 to 6 km','latitude'=>22.4370,'longitude'=>88.4260,'meta_title'=>'AC Service in Sonarpur | Repair, Installation & AMC | Cooling Kolkata','meta_description'=>'AC repair & servicing in Sonarpur (Station Road area), Kolkata 700150. Certified technicians, genuine parts. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Sonarpur, Kolkata – 700150','intro_text'=>'Cooling Kolkata provides onsite AC repair and Annual Maintenance Contracts (AMC) in Sonarpur, covering the Station Road and entry areas (PIN 700150). Transparent pricing with no hidden charges.','is_active'=>1,'sort_order'=>9,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Tollygunge, Ranikuthi & Netaji Nagar','slug'=>'tollygunge-ranikuthi-netaji-nagar','zone'=>'Central-South & Tollygunge Zone','zone_slug'=>'central-south-tollygunge','pin_codes'=>'["700040","700033"]','distance_km'=>'4 to 7 km','latitude'=>22.4960,'longitude'=>88.3490,'meta_title'=>'AC Service in Tollygunge | Ranikuthi & Netaji Nagar AC Repair | Cooling Kolkata','meta_description'=>'AC repair & servicing in Tollygunge, Ranikuthi, Netaji Nagar & Karunamoyee, Kolkata (700040 / 700033). Fast onsite service. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Tollygunge, Ranikuthi & Netaji Nagar, Kolkata','intro_text'=>'Cooling Kolkata serves the Tollygunge metro corridor including Ranikuthi, Netaji Nagar, and Karunamoyee (PIN 700040 / 700033) with expert AC repair, installation, and preventive maintenance.','is_active'=>1,'sort_order'=>10,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Gariahat, Golpark & Ballygunge','slug'=>'gariahat-golpark-ballygunge','zone'=>'Central-South & Tollygunge Zone','zone_slug'=>'central-south-tollygunge','pin_codes'=>'["700019"]','distance_km'=>'4 to 7 km','latitude'=>22.5220,'longitude'=>88.3650,'meta_title'=>'AC Service in Gariahat & Ballygunge | Golpark AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Gariahat, Golpark & Ballygunge, Kolkata 700019. Certified technicians. Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Gariahat, Golpark & Ballygunge, Kolkata – 700019','intro_text'=>'Cooling Kolkata covers Gariahat, Golpark, and Ballygunge (PIN 700019) with premium AC repair and maintenance. Residential split AC or commercial VRF system, our certified technicians deliver on the same day.','is_active'=>1,'sort_order'=>11,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Rasbehari & Hazra','slug'=>'rasbehari-hazra','zone'=>'Central-South & Tollygunge Zone','zone_slug'=>'central-south-tollygunge','pin_codes'=>'["700026"]','distance_km'=>'4 to 7 km','latitude'=>22.5270,'longitude'=>88.3570,'meta_title'=>'AC Service in Rasbehari & Hazra | Repair & Maintenance | Cooling Kolkata','meta_description'=>'AC repair & servicing in Rasbehari & Hazra, Kolkata 700026. Same-day onsite service by certified technicians. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Rasbehari & Hazra, Kolkata – 700026','intro_text'=>'Cooling Kolkata brings expert AC repair, gas charging, and annual maintenance to Rasbehari and Hazra (PIN 700026). Our technicians respond fast across this busy South Kolkata belt, 6 days a week.','is_active'=>1,'sort_order'=>12,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Kudghat, Haridevpur & Chanditala','slug'=>'kudghat-haridevpur-chanditala','zone'=>'Central-South & Tollygunge Zone','zone_slug'=>'central-south-tollygunge','pin_codes'=>'["700082","700041"]','distance_km'=>'4 to 7 km','latitude'=>22.4780,'longitude'=>88.3300,'meta_title'=>'AC Service in Kudghat & Haridevpur | Chanditala AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Kudghat, Haridevpur & Chanditala, Kolkata (700082 / 700041). Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Kudghat, Haridevpur & Chanditala, Kolkata','intro_text'=>'Cooling Kolkata covers Kudghat, Haridevpur, and Chanditala (PIN 700082 / 700041) for all AC repair and servicing needs. From filter cleaning to full compressor replacement, transparent pricing.','is_active'=>1,'sort_order'=>13,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Behala','slug'=>'behala','zone'=>'Central-South & Tollygunge Zone','zone_slug'=>'central-south-tollygunge','pin_codes'=>'["700034"]','distance_km'=>'4 to 7 km','latitude'=>22.4892,'longitude'=>88.3140,'meta_title'=>'AC Service in Behala | Chaurasta & Tram Depot AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Behala (Chaurasta & Tram Depot area), Kolkata 700034. Same-day service. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Behala, Kolkata – 700034','intro_text'=>'Cooling Kolkata serves Behala Chaurasta and Tram Depot areas (PIN 700034) with reliable AC repair, installation, and AMC plans. Fast response, no hidden charges, certified technicians for all major brands.','is_active'=>1,'sort_order'=>14,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Topsia, Tiljala & Science City','slug'=>'topsia-tiljala-science-city','zone'=>'Science City & Bhawanipore Zone','zone_slug'=>'science-city-bhawanipore','pin_codes'=>'["700046","700105"]','distance_km'=>'6 to 8 km','latitude'=>22.5410,'longitude'=>88.3950,'meta_title'=>'AC Service in Topsia & Tiljala | Science City Area AC Repair | Cooling Kolkata','meta_description'=>'AC repair, installation & servicing in Topsia, Tiljala & Science City area, Kolkata (700046 / 700105). Certified technicians. Call +91 8346904100.','page_heading'=>'AC Repair & Service in Topsia, Tiljala & Science City, Kolkata','intro_text'=>'Cooling Kolkata covers Topsia, Tiljala, and the Science City corridor (PIN 700046 / 700105) with onsite AC repair, installation, and commercial HVAC maintenance. Available Monday to Saturday.','is_active'=>1,'sort_order'=>15,'created_at'=>$now,'updated_at'=>$now],
    ['name'=>'Bhawanipore & Sarat Bose Road','slug'=>'bhawanipore-sarat-bose-road','zone'=>'Science City & Bhawanipore Zone','zone_slug'=>'science-city-bhawanipore','pin_codes'=>'["700025","700020"]','distance_km'=>'6 to 8 km','latitude'=>22.5340,'longitude'=>88.3510,'meta_title'=>'AC Service in Bhawanipore & Sarat Bose Road | Repair & Installation | Cooling Kolkata','meta_description'=>'AC repair & servicing in Bhawanipore & Sarat Bose Road, Kolkata (700025 / 700020). Expert onsite service. Call Cooling Kolkata at +91 8346904100.','page_heading'=>'AC Repair & Service in Bhawanipore & Sarat Bose Road, Kolkata','intro_text'=>'Cooling Kolkata brings reliable AC repair and servicing to Bhawanipore and Sarat Bose Road (PIN 700025 / 700020). Trusted by residential and commercial clients across this South-Central Kolkata zone.','is_active'=>1,'sort_order'=>16,'created_at'=>$now,'updated_at'=>$now],
];

DB::table('service_areas')->insert($areas);
echo 'Done! '.DB::table('service_areas')->count().' areas inserted.'.PHP_EOL;
